(function(){
'use strict';
const families=[
{id:'ie',name:'INDO-EUROPEAN',x:-720,y:80,c:'#786b49',note:'Germanic · Romance · Indo-Iranian · Slavic and other branches'},
{id:'st',name:'SINO-TIBETAN',x:1040,y:-360,c:'#6f5f87',note:'Sinitic and Tibeto-Burman branches'},
{id:'aa',name:'AFRO-ASIATIC',x:520,y:820,c:'#8a6747',note:'Semitic and other branches'},
{id:'an',name:'AUSTRONESIAN',x:1750,y:620,c:'#47767d',note:'Malayic · Javanic · Philippine and Pacific branches'},
{id:'nc',name:'NIGER-CONGO',x:180,y:760,c:'#52774f',note:'Including Bantu languages such as Swahili'},
{id:'dr',name:'DRAVIDIAN',x:1080,y:700,c:'#7d594e',note:'South and South-Central Dravidian'},
{id:'tu',name:'TURKIC',x:260,y:-520,c:'#7b7043',note:'Oghuz and other Turkic branches'},
{id:'ja',name:'JAPONIC',x:1960,y:-420,c:'#8b5664',note:'Japanese and Ryukyuan languages'},
{id:'ko',name:'KOREANIC',x:1560,y:-520,c:'#6a6487',note:'Korean and historical Koreanic varieties'},
{id:'au',name:'AUSTROASIATIC',x:1320,y:240,c:'#5d7865',note:'Vietic, Khmer and other branches'},
{id:'kd',name:'KRA–DAI',x:1580,y:160,c:'#657b55',note:'Tai and related branches'},
{id:'ur',name:'URALIC',x:-40,y:-820,c:'#54717b',note:'Finnic, Ugric and related branches'}
];
const langs=[
['English','ie','Germanic','Old English / Middle English / Proto-Germanic','en',-1260,-220,'English','Latin script'],['Spanish','ie','Romance','Latin','es',-930,380,'español','Latin script'],['French','ie','Romance','Latin','fr',-650,430,'français','Latin script'],['Portuguese','ie','Romance','Latin','pt',-1080,470,'português','Latin script'],['Italian','ie','Romance','Latin','it',-420,430,'italiano','Latin script'],['German','ie','Germanic','Proto-Germanic','de',-1060,-420,'Deutsch','Latin script'],['Dutch','ie','Germanic','Proto-Germanic','nl',-860,-360,'Nederlands','Latin script'],['Russian','ie','Slavic','Proto-Slavic','ru',-280,-80,'русский','Cyrillic'],['Ukrainian','ie','Slavic','Proto-Slavic','uk',-100,20,'українська','Cyrillic'],['Polish','ie','Slavic','Proto-Slavic','pl',-350,100,'polski','Latin script'],['Hindi','ie','Indo-Aryan','Sanskrit / Prakrit','hi',-300,380,'हिन्दी','Devanagari'],['Urdu','ie','Indo-Aryan','Hindustani + Persian/Arabic influence','ur',-100,500,'اردو','Perso-Arabic'],['Bengali','ie','Indo-Aryan','Magadhi Prakrit','bn',100,430,'বাংলা','Bengali script'],['Marathi','ie','Indo-Aryan','Maharashtri Prakrit','mr',-60,260,'मराठी','Devanagari'],['Punjabi','ie','Indo-Aryan','Shauraseni / regional Prakrits','pa',160,270,'ਪੰਜਾਬੀ / پنجابی','Gurmukhi / Shahmukhi'],['Gujarati','ie','Indo-Aryan','Gurjar Apabhramsha','gu',-220,190,'ગુજરાતી','Gujarati script'],['Persian','ie','Iranian','Middle Persian','fa',230,330,'فارسی','Perso-Arabic'],
['Mandarin Chinese','st','Sinitic','Middle Chinese / Old Chinese','zh',1040,-520,'普通话 / 國語','Chinese characters'],['Cantonese','st','Sinitic','Middle Chinese','yue',1210,-330,'粵語','Chinese characters'],['Burmese','st','Burmic','Old Burmese','my',880,-180,'မြန်မာဘာသာ','Burmese script'],
['Arabic','aa','Semitic','Proto-Semitic / Classical Arabic','ar',520,650,'العربية','Arabic script'],['Hausa','aa','Chadic','Proto-Chadic','ha',260,920,'Hausa','Latin / Ajami'],['Amharic','aa','Ethio-Semitic','Geʽez / Proto-Ethio-Semitic','am',760,940,'አማርኛ','Geʽez script'],
['Indonesian','an','Malayic','Classical Malay','id',1650,520,'Bahasa Indonesia','Latin script'],['Malay','an','Malayic','Classical Malay','ms',1840,480,'Bahasa Melayu','Latin / Jawi'],['Javanese','an','Javanic','Old Javanese','jv',1750,760,'Basa Jawa','Latin / Javanese'],['Filipino / Tagalog','an','Philippine','Old Tagalog / Proto-Philippine','tl',2020,660,'Filipino / Tagalog','Latin script'],
['Swahili','nc','Bantu','Proto-Sabaki / Proto-Bantu','sw',180,760,'Kiswahili','Latin script'],
['Tamil','dr','South Dravidian','Old Tamil / Proto-Dravidian','ta',930,670,'தமிழ்','Tamil script'],['Telugu','dr','South-Central Dravidian','Old Telugu / Proto-Dravidian','te',1170,580,'తెలుగు','Telugu script'],['Kannada','dr','South Dravidian','Old Kannada / Proto-Dravidian','kn',920,880,'ಕನ್ನಡ','Kannada script'],['Malayalam','dr','South Dravidian','Middle Tamil / Proto-Dravidian','ml',1210,860,'മലയാളം','Malayalam script'],
['Turkish','tu','Oghuz Turkic','Old Anatolian Turkish / Proto-Turkic','tr',260,-520,'Türkçe','Latin script'],
['Japanese','ja','Japonic','Old Japanese / Proto-Japonic','ja',1960,-420,'日本語','Kanji + kana'],['Korean','ko','Koreanic','Middle Korean / Proto-Koreanic','ko',1560,-520,'한국어 / 조선말','Hangul'],
['Vietnamese','au','Vietic','Proto-Vietic + heavy Sinitic influence','vi',1320,240,'Tiếng Việt','Latin script'],['Thai','kd','Tai','Old Thai / Proto-Tai','th',1580,160,'ภาษาไทย','Thai script'],
['Hungarian','ur','Ugric','Proto-Ugric / Old Hungarian','hu',-40,-820,'magyar','Latin script']
].map((a,i)=>({name:a[0],family:a[1],branch:a[2],history:a[3],code:a[4],x:a[5],y:a[6],native:a[7],script:a[8],i}));
const familyBy=Object.fromEntries(families.map(f=>[f.id,f]));
const langBy=Object.fromEntries(langs.map(l=>[l.name.toLowerCase(),l]));
const ancestors=[
['pie','Proto-Indo-European',-720,0,'ie'],['pg','Proto-Germanic',-1080,-520,'ie'],['latin','Latin',-700,570,'ie'],['pslav','Proto-Slavic',-180,100,'ie'],['sanskrit','Sanskrit / Middle Indo-Aryan',-30,460,'ie'],['piran','Proto-Iranian / Middle Persian',220,450,'ie'],
['pst','Proto-Sino-Tibetan',1040,-120,'st'],['och','Old / Middle Chinese',1160,-520,'st'],['pbur','Proto-Burmic / Old Burmese',820,-140,'st'],
['paa','Proto-Afro-Asiatic',520,1080,'aa'],['psem','Proto-Semitic',590,820,'aa'],['pchad','Proto-Chadic',250,1030,'aa'],['geez','Geʽez / Ethio-Semitic',790,1030,'aa'],
['pan','Proto-Austronesian',1750,940,'an'],['pmp','Proto-Malayo-Polynesian',1760,760,'an'],['pmalay','Proto-Malayic / Classical Malay',1740,570,'an'],['pphil','Proto-Philippine',2020,820,'an'],
['pnc','Niger-Congo family-level node',180,1080,'nc'],['pbantu','Bantu / Sabaki lineage',180,900,'nc'],
['pdr','Proto-Dravidian',1080,1050,'dr'],['psd','Proto-South Dravidian',1000,900,'dr'],
['pturk','Proto-Turkic',260,-700,'tu'],['poj','Old Turkic / Oghuz',260,-610,'tu'],
['pjap','Proto-Japonic / Old Japanese',1960,-620,'ja'],['pkor','Proto-Koreanic / Middle Korean',1560,-700,'ko'],['paaustro','Proto-Austroasiatic',1320,440,'au'],['pviet','Proto-Vietic',1320,330,'au'],['pkd','Proto-Kra–Dai',1580,360,'kd'],['ptai','Proto-Tai',1580,260,'kd'],['pural','Proto-Uralic',-40,-1000,'ur'],['pugric','Proto-Ugric / Old Hungarian',-40,-900,'ur']
].map(a=>({id:a[0],name:a[1],x:a[2],y:a[3],family:a[4]}));
const ancBy=Object.fromEntries(ancestors.map(a=>[a.id,a]));
const lineage=[];function L(a,b){lineage.push([a,b])}
L('pie','pg');L('pg','English');L('pg','German');L('pg','Dutch');L('pie','latin');['Spanish','French','Portuguese','Italian'].forEach(x=>L('latin',x));L('pie','pslav');['Russian','Ukrainian','Polish'].forEach(x=>L('pslav',x));L('pie','sanskrit');['Hindi','Urdu','Bengali','Marathi','Punjabi','Gujarati'].forEach(x=>L('sanskrit',x));L('pie','piran');L('piran','Persian');
L('pst','och');L('och','Mandarin Chinese');L('och','Cantonese');L('pst','pbur');L('pbur','Burmese');
L('paa','psem');L('psem','Arabic');L('paa','pchad');L('pchad','Hausa');L('psem','geez');L('geez','Amharic');
L('pan','pmp');L('pmp','pmalay');L('pmalay','Indonesian');L('pmalay','Malay');L('pmp','Javanese');L('pmp','pphil');L('pphil','Filipino / Tagalog');
L('pnc','pbantu');L('pbantu','Swahili');L('pdr','psd');['Tamil','Kannada','Malayalam'].forEach(x=>L('psd',x));L('pdr','Telugu');L('pturk','poj');L('poj','Turkish');L('pjap','Japanese');L('pkor','Korean');L('paaustro','pviet');L('pviet','Vietnamese');L('pkd','ptai');L('ptai','Thai');L('pural','pugric');L('pugric','Hungarian');
const borrow=[
['French','English','Norman/French vocabulary'],['Latin','English','learned and ecclesiastical vocabulary'],['Arabic','Spanish','centuries of contact in Iberia'],['Arabic','English','science, trade and mediated loans'],['Persian','Urdu','major literary and administrative influence'],['Persian','Hindi','shared Hindustani/Persianate vocabulary'],['Sanskrit / Middle Indo-Aryan','Hindi','core Indo-Aryan inheritance and learned loans'],['Sanskrit / Middle Indo-Aryan','Bengali','inheritance and learned vocabulary'],['Old / Middle Chinese','Japanese','Sino-Japanese vocabulary'],['Old / Middle Chinese','Korean','Sino-Korean vocabulary'],['Old / Middle Chinese','Vietnamese','Sino-Vietnamese vocabulary'],['Arabic','Swahili','Indian Ocean trade vocabulary'],['English','Japanese','modern loanwords'],['English','Indonesian','modern technical/global vocabulary'],['English','Hindi','modern technical/global vocabulary'],['Arabic','Indonesian','religious and trade vocabulary'],['Malay','English','maritime/tropical borrowings'],['Turkish','English','selected cultural borrowings']
];
const st=document.createElement('style');st.textContent=`#worldLangLayer{position:fixed;inset:0;z-index:2;display:none;background:#040806;touch-action:none}body.world-mode #worldLangLayer{display:block}body.world-mode #c{opacity:.06}.world-chip{position:fixed;z-index:4;left:14px;top:112px;padding:7px 10px;border-radius:11px;background:#07120cdd;border:1px solid #bcefc026;color:#a9c2af;font:10px system-ui;display:none}body.world-mode .world-chip{display:block}@media(max-width:760px){.world-chip{top:142px;left:10px}}`;document.head.appendChild(st);
const WC=document.createElement('canvas');WC.id='worldLangLayer';document.body.insertBefore(WC,document.querySelector('.top'));const WX=WC.getContext('2d');const chip=document.createElement('div');chip.className='world-chip';chip.textContent='WORLD · families → languages · dashed lines = borrowing highways';document.body.appendChild(chip);
let WW,WH,WD;function wr(){WW=innerWidth;WH=innerHeight;WD=Math.min(devicePixelRatio||1,2);WC.width=WW*WD;WC.height=WH*WD;WX.setTransform(WD,0,0,WD,0,0)}wr();addEventListener('resize',wr);
let wcam={x:520,y:180,z:.33},wtar={...wcam},world=false,wsel=null;const wsx=v=>(v-wcam.x)*wcam.z+WW/2,wsy=v=>(v-wcam.y)*wcam.z+WH/2,wwx=v=>(v-WW/2)/wcam.z+wcam.x,wwy=v=>(v-WH/2)/wcam.z+wcam.y;
function nodePos(id){return ancBy[id]||ancestors.find(a=>a.name===id)||langBy[id.toLowerCase()]||langs.find(l=>l.name===id)}
function worldPanel(o){if(!o)return;const f=familyBy[o.family];if(o.code){P.innerHTML=`<div class="eye">world language forest</div><h2>${o.name}</h2><p>${o.native}<br>${f.name} · ${o.branch}<br>${o.script}</p><div class="meta">Historical path: ${o.history}.<br>World mode maps language ancestry and major borrowing highways. ${o.name==='English'?'Enter English to descend into the full word/IPA/sound-change forest.':'Lexeme-level expansion for this language can be layered in without changing the world atlas.'}</div>${o.name==='English'?'<button id="enterEnglish" style="margin-top:10px;border:1px solid #bcefc02d;background:#17331f;color:#eef8f0;border-radius:10px;padding:8px 11px">Enter English word forest</button>':''}`;if(o.name==='English')setTimeout(()=>{const b=document.querySelector('#enterEnglish');if(b)b.onclick=()=>setWorld(false)},0);return}P.innerHTML=`<div class="eye">family / historical stage</div><h2>${o.name}</h2><p>${f.name}</p><div class="meta">This node connects major modern language forests. Some deep nodes are family-level or reconstructed stages rather than directly attested languages; contested macro-family claims are intentionally omitted. Solid lines show genealogical descent at this scale, while dashed lines show borrowing/influence corridors.</div>`}
function setWorld(v){world=v;document.body.classList.toggle('world-mode',world);worldBtn.textContent=world?'English':'World';const ipa=document.querySelector('#ipa-layer');if(ipa)ipa.style.visibility=world?'hidden':'';for(const q of ['#change-layer','#soundchange-layer']){const e=document.querySelector(q);if(e)e.style.visibility=world?'hidden':''}if(world){wsel=null;wtar={x:520,y:180,z:.33};P.innerHTML='<div class="eye">world forest</div><h2>Major languages</h2><p>Zoom from language families into modern languages and historical stages.</p><div class="meta">Solid branches = genealogical descent. Dashed amber routes = major borrowing/influence corridors. Deep or disputed reconstructions are not treated as certain. English remains the deepest lexeme-level forest in this build.</div>'}else{try{panel()}catch(_){}}}
const worldBtn=document.createElement('button');worldBtn.id='worldMode';worldBtn.textContent='World';worldBtn.title='Toggle world language forest';document.querySelector('.btns').insertBefore(worldBtn,document.querySelector('.btns').firstChild);worldBtn.onclick=()=>setWorld(!world);
function drawWorld(){requestAnimationFrame(drawWorld);if(!world)return;wcam.x+=(wtar.x-wcam.x)*.1;wcam.y+=(wtar.y-wcam.y)*.1;wcam.z+=(wtar.z-wcam.z)*.1;WX.fillStyle='#040806';WX.fillRect(0,0,WW,WH);
for(const f of families){const ls=langs.filter(l=>l.family===f.id),cx=wsx(f.x),cy=wsy(f.y),rad=(210+ls.length*18)*wcam.z,g=WX.createRadialGradient(cx,cy,0,cx,cy,rad*1.8);g.addColorStop(0,f.c+'44');g.addColorStop(1,f.c+'00');WX.fillStyle=g;WX.beginPath();WX.arc(cx,cy,rad*1.8,0,Math.PI*2);WX.fill();if(wcam.z<.78){WX.fillStyle='#c1d2c5aa';WX.font='700 '+Math.max(11,17*wcam.z)+'px system-ui';WX.textAlign='center';WX.fillText(f.name,cx,cy-rad*.85)}}
WX.lineCap='round';for(const [a,b] of lineage){const A=nodePos(a),B=nodePos(b);if(!A||!B)continue;WX.beginPath();WX.moveTo(wsx(A.x),wsy(A.y));WX.lineTo(wsx(B.x),wsy(B.y));WX.strokeStyle='#9fc3a46e';WX.lineWidth=Math.max(1,1.7*wcam.z);WX.setLineDash([]);WX.stroke()}
for(const [a,b] of borrow){const A=nodePos(a),B=nodePos(b);if(!A||!B)continue;WX.beginPath();WX.moveTo(wsx(A.x),wsy(A.y));const x1=wsx(A.x),y1=wsy(A.y),x2=wsx(B.x),y2=wsy(B.y),mx=(x1+x2)/2,my=(y1+y2)/2,dx=x2-x1,dy=y2-y1;WX.quadraticCurveTo(mx-dy*.12,my+dx*.12,x2,y2);WX.strokeStyle='#e2a46e99';WX.lineWidth=1.35;WX.setLineDash([5,5]);WX.stroke()}WX.setLineDash([]);
for(const a of ancestors){const sel=wsel===a;WX.fillStyle=sel?'#fff3c4':'#d7bd7b';WX.globalAlpha=sel?1:.65;WX.beginPath();WX.arc(wsx(a.x),wsy(a.y),(sel?7:4)*Math.max(.8,wcam.z),0,Math.PI*2);WX.fill();if(wcam.z>.55||sel){WX.fillStyle='#d8e6db';WX.font=(sel?'700 ':'500 ')+'11px system-ui';WX.textAlign='center';WX.fillText(a.name,wsx(a.x),wsy(a.y)-9)}}WX.globalAlpha=1;
for(const l of langs){const sel=wsel===l,f=familyBy[l.family];WX.fillStyle=sel?'#ffffff':f.c;WX.globalAlpha=sel?1:.92;WX.beginPath();WX.arc(wsx(l.x),wsy(l.y),(sel?8:5)*Math.max(.85,wcam.z),0,Math.PI*2);WX.fill();if(wcam.z>.46||sel){WX.fillStyle='#eef8f0';WX.font=(sel?'700 ':'600 ')+Math.max(9,12*wcam.z)+'px system-ui';WX.textAlign='center';WX.fillText(l.name,wsx(l.x),wsy(l.y)-10);if(wcam.z>1.05){WX.fillStyle='#91a898';WX.font='9px system-ui';WX.fillText(l.native,wsx(l.x),wsy(l.y)+14)}}WX.globalAlpha=1}}
drawWorld();
function worldSearch(q){q=q.trim().toLowerCase();if(!q)return;let l=langBy[q]||langs.find(x=>x.name.toLowerCase().startsWith(q)||x.native.toLowerCase().includes(q));if(l){wsel=l;wtar.x=l.x;wtar.y=l.y;wtar.z=Math.max(wtar.z,.95);worldPanel(l);return true}let f=families.find(x=>x.name.toLowerCase().includes(q));if(f){wsel=null;wtar.x=f.x;wtar.y=f.y;wtar.z=.55;P.innerHTML=`<div class="eye">language family</div><h2>${f.name}</h2><p>${f.note}</p><div class="meta">${langs.filter(l=>l.family===f.id).map(l=>l.name).join(' · ')}</div>`;return true}return false}
const go=document.querySelector('#go'),qin=document.querySelector('#q');go.addEventListener('click',e=>{if(!world)return;e.preventDefault();e.stopImmediatePropagation();if(!worldSearch(qin.value))toast('Language or family not loaded yet')},true);qin.addEventListener('keydown',e=>{if(!world||e.key!=='Enter')return;e.preventDefault();e.stopImmediatePropagation();if(!worldSearch(qin.value))toast('Language or family not loaded yet')},true);
let pts=new Map(),pinch=0,moved=0;WC.onpointerdown=e=>{if(!world)return;pts.set(e.pointerId,[e.clientX,e.clientY]);WC.setPointerCapture(e.pointerId);moved=0};WC.onpointermove=e=>{if(!pts.has(e.pointerId))return;let old=pts.get(e.pointerId);pts.set(e.pointerId,[e.clientX,e.clientY]);if(pts.size===1){let dx=e.clientX-old[0],dy=e.clientY-old[1];if(Math.hypot(dx,dy)>2)moved=1;wcam.x=wtar.x-=dx/wcam.z;wcam.y=wtar.y-=dy/wcam.z}else{let p=[...pts.values()],d=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]),mx=(p[0][0]+p[1][0])/2,my=(p[0][1]+p[1][1])/2;if(pinch){let bx=wwx(mx),byy=wwy(my),z=Math.max(.16,Math.min(3,wcam.z*d/pinch));wcam.z=wtar.z=z;wcam.x=wtar.x=bx-(mx-WW/2)/z;wcam.y=wtar.y=byy-(my-WH/2)/z}pinch=d;moved=1}};function wup(e){pts.delete(e.pointerId);if(pts.size<2)pinch=0}WC.onpointerup=wup;WC.onpointercancel=wup;WC.addEventListener('wheel',e=>{if(!world)return;e.preventDefault();let bx=wwx(e.clientX),byy=wwy(e.clientY),z=Math.max(.16,Math.min(3,wcam.z*Math.exp(-e.deltaY*.0012)));wcam.z=wtar.z=z;wcam.x=wtar.x=bx-(e.clientX-WW/2)/z;wcam.y=wtar.y=byy-(e.clientY-WH/2)/z},{passive:false});WC.onclick=e=>{if(!world||moved)return;let best=null,d=25;for(const l of langs){let q=Math.hypot(wsx(l.x)-e.clientX,wsy(l.y)-e.clientY);if(q<d){d=q;best=l}}for(const a of ancestors){let q=Math.hypot(wsx(a.x)-e.clientX,wsy(a.y)-e.clientY);if(q<d){d=q;best=a}}if(best){wsel=best;wtar.x=best.x;wtar.y=best.y;wtar.z=Math.max(wtar.z,.9);worldPanel(best)}};
const oldStatus=status;status=function(){if(world){S.textContent='world · '+Math.round(wcam.z*100)+'% · '+families.length+' families · '+langs.length+' major languages · '+borrow.length+' borrowing highways';return}return oldStatus()};
const sm=document.querySelector('.brand small');if(sm)sm.textContent='Phase 5 · World Language Forest';
setWorld(true);try{status()}catch(_){ }
})();
