(function(){'use strict';
const lex=window.__worldLexicons||{}, F=window.families||[], L=window.langs||[], A=window.ancestors||[], LE=window.lineage||[], BO=window.borrow||[];
const panel=document.querySelector('.panel'), S=document.querySelector('.status');
const ENS=(typeof ns!=='undefined'?ns:[]), EES=(typeof es!=='undefined'?es:[]), EBY=(typeof by!=='undefined'?by:{}), ELC=(typeof LC!=='undefined'?LC:{}), EEC=(typeof EC!=='undefined'?EC:{});
const css=document.createElement('style'); css.textContent=`
body.temporal-world #writingUniverse,body.temporal-world #semanticUniverse,body.temporal-world #unifiedUniverse,body.temporal-world #c,body.temporal-world #worldLangLayer,body.temporal-world #lexiconLayer{opacity:0!important;pointer-events:none!important}
body.temporal-world #ipa-layer,body.temporal-world #sound-layer{display:none!important}
#timeUniverse{position:fixed;inset:0;z-index:5;width:100%;height:100%;background:#040806;touch-action:none}
.time-chip{position:fixed;z-index:11;left:14px;top:112px;padding:7px 10px;border-radius:10px;background:#06110bed;border:1px solid #e7c98526;color:#b9c9bd;font:9px system-ui;letter-spacing:.05em;pointer-events:none}
.time-bar{position:fixed;z-index:12;left:50%;bottom:14px;transform:translateX(-50%);width:min(820px,calc(100vw - 28px));padding:9px 11px 8px;border-radius:13px;background:#06110bf2;border:1px solid #e7c9852c;box-shadow:0 12px 40px #000a;backdrop-filter:blur(10px)}
.time-row{display:flex;align-items:center;gap:8px}.time-row button{border:1px solid #d7bd7b30;background:#17170e;color:#f2e7c4;border-radius:8px;padding:5px 8px;font:10px system-ui}.time-year{min-width:88px;text-align:center;color:#fff0c5;font:700 13px ui-monospace,monospace}.time-range{flex:1;accent-color:#d7bd7b}.time-scale{display:flex;justify-content:space-between;margin:4px 42px 0;color:#758b7b;font:8px system-ui}.time-note{margin-top:5px;color:#829889;font:8px/1.3 system-ui}.time-events{position:fixed;z-index:10;right:14px;bottom:84px;width:min(310px,calc(100vw - 28px));padding:8px 10px;border-radius:10px;background:#06110bd9;border:1px solid #bcefc018;color:#95aa9b;font:9px/1.35 system-ui;pointer-events:none}.time-events b{color:#dfeadf}
#timeBtn.on{background:#5a4a23!important;box-shadow:0 0 15px #e7c98525 inset}
@media(max-width:760px){.time-chip{left:10px;top:142px;max-width:calc(100vw - 20px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.time-bar{bottom:10px;width:calc(100vw - 20px)}.time-scale{margin-left:0;margin-right:0}.time-events{display:none}}
`; document.head.appendChild(css);
const U=document.createElement('canvas');U.id='timeUniverse';document.body.insertBefore(U,document.querySelector('.top'));const G=U.getContext('2d');
const chip=document.createElement('div');chip.className='time-chip';document.body.appendChild(chip);
const bar=document.createElement('div');bar.className='time-bar';bar.innerHTML=`<div class="time-row"><button id="timePlay">▶</button><button id="timeNow">Now</button><div class="time-year" id="timeYear">2026 CE</div><input class="time-range" id="timeRange" type="range" min="-4500" max="2026" step="25" value="2026"></div><div class="time-scale"><span>4500 BCE</span><span>3000 BCE</span><span>1500 BCE</span><span>1 CE</span><span>1000</span><span>1500</span><span>2026</span></div><div class="time-note">Broad historical model. Script and major language-stage dates are approximate ranges; many lexeme dates are heuristic until source-backed.</div>`;document.body.appendChild(bar);
const eventsBox=document.createElement('div');eventsBox.className='time-events';document.body.appendChild(eventsBox);
const slider=bar.querySelector('#timeRange'),yearEl=bar.querySelector('#timeYear'),playBtn=bar.querySelector('#timePlay'),nowBtn=bar.querySelector('#timeNow');
let year=2026,playing=false,timer=null,W=0,H=0,D=1,cam={x:430,y:100,z:.33},tar={x:430,y:100,z:.33},pts=new Map(),pinch=0,moved=0,hit=null,writingOn=true,cognates=true,ipaOn=true,changesOn=true;
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);U.width=W*D;U.height=H*D;G.setTransform(D,0,0,D,0,0)}resize();addEventListener('resize',resize);
const sx=x=>(x-cam.x)*cam.z+W/2,sy=y=>(y-cam.y)*cam.z+H/2,wx=x=>(x-W/2)/cam.z+cam.x,wy=y=>(y-H/2)/cam.z+cam.y;
const LBY=Object.fromEntries(L.map(l=>[l.name,l])),ABY=Object.fromEntries(A.map(a=>[a.id,a])),FBY=Object.fromEntries(F.map(f=>[f.id,f])),EN=LBY.English;
const exMin=ENS.length?Math.min(...ENS.map(n=>n.x)):0,exMax=ENS.length?Math.max(...ENS.map(n=>n.x)):0,eyMin=ENS.length?Math.min(...ENS.map(n=>n.y)):0,eyMax=ENS.length?Math.max(...ENS.map(n=>n.y)):0,exCx=(exMin+exMax)/2,exCy=(eyMin+eyMax)/2,ES=.155;
function exPos(n){return{x:EN.x+(n.x-exCx)*ES,y:EN.y+(n.y-exCy)*ES}}
function hash32(s){let h=2166136261;for(const ch of String(s))h=Math.imul(h^ch.charCodeAt(0),16777619);return h>>>0}
function microPos(l,w,i,total){const h=hash32(l.name+'|'+w.f),a=(h%100000)/100000*Math.PI*2,r=(78+((h>>>9)%100)/100*92)*(total>16?1.08:1);return{x:l.x+Math.cos(a)*r,y:l.y+Math.sin(a)*r}}
function npos(id){return ABY[id]||A.find(a=>a.name===id)||LBY[id]}
function visible(x,y,p=70){const X=sx(x),Y=sy(y);return X>-p&&X<W+p&&Y>-p&&Y<H+p}
function line(a,b,color,w=1,dash=null,curve=0){if(!a||!b)return;const X1=sx(a.x),Y1=sy(a.y),X2=sx(b.x),Y2=sy(b.y);G.beginPath();G.moveTo(X1,Y1);if(curve){const mx=(X1+X2)/2,my=(Y1+Y2)/2,dx=X2-X1,dy=Y2-Y1;G.quadraticCurveTo(mx-dy*curve,my+dx*curve,X2,Y2)}else G.lineTo(X2,Y2);G.strokeStyle=color;G.lineWidth=w;G.setLineDash(dash||[]);G.stroke();G.setLineDash([])}
function fmt(y){return y<=0?Math.abs(y||1)+' BCE':y+' CE'}
function fade(start,end=9999){const fIn=Math.max(0,Math.min(1,(year-start)/140));if(year<start)return 0;if(year<=end)return fIn;return Math.max(0,1-(year-end)/180)}
function active(start,end=9999){return fade(start,end)>0}
function stage(){return cam.z<.42?'FAMILY':cam.z<.72?'LANGUAGE':cam.z<1.12?'FOREST':cam.z<1.72?'WORD':'PHONETIC'}
const FAMILY_START={ie:-4500,st:-4000,aa:-5000,an:-3000,nc:-4000,dr:-3000,tu:-1000,ja:-1000,ko:-1000,au:-2500,kd:-1500,ur:-2500};
const ASTART={pie:[-4500,-2500],pg:[-500,450],latin:[-700,700],pslav:[500,1000],sanskrit:[-1500,1000],piran:[-1200,700],pst:[-4000,-1500],och:[-1200,900],pbur:[600,1200],paa:[-5000,-2500],psem:[-2500,600],pchad:[-2500,800],geez:[100,1200],pan:[-3000,-1500],pmp:[-1500,500],pmalay:[500,1400],pphil:[-500,1200],pnc:[-4000,-1500],pbantu:[-1000,900],pdr:[-3000,-1000],psd:[-1000,500],pturk:[-1000,500],poj:[600,1200],pjap:[-1000,700],pkor:[-1000,600],paaustro:[-2500,-800],pviet:[-800,900],pkd:[-1500,-500],ptai:[-500,1200],pural:[-2500,-800],pugric:[-800,900]};
const LSTART={'English':450,'Spanish':900,'French':800,'Portuguese':1100,'Italian':900,'German':500,'Dutch':500,'Russian':1000,'Ukrainian':1100,'Polish':900,'Hindi':1200,'Urdu':1200,'Bengali':1000,'Marathi':1000,'Punjabi':1000,'Gujarati':1100,'Persian':800,'Mandarin Chinese':1300,'Cantonese':900,'Burmese':1100,'Arabic':600,'Hausa':1000,'Amharic':1200,'Indonesian':1900,'Malay':1300,'Javanese':800,'Filipino / Tagalog':1500,'Swahili':900,'Tamil':-300,'Telugu':600,'Kannada':500,'Malayalam':900,'Turkish':1000,'Japanese':700,'Korean':600,'Vietnamese':900,'Thai':1200,'Hungarian':900};
const BSTART={'French|English':1066,'Latin|English':600,'Arabic|Spanish':711,'Arabic|English':1200,'Persian|Urdu':1200,'Persian|Hindi':1200,'Old / Middle Chinese|Japanese':500,'Old / Middle Chinese|Korean':500,'Old / Middle Chinese|Vietnamese':200,'Arabic|Swahili':900,'English|Japanese':1850,'English|Indonesian':1800,'English|Hindi':1800,'Arabic|Indonesian':1200,'Malay|English':1500,'Turkish|English':1500};
const SCRIPT=[
['proto-sinaitic','Proto-Sinaitic',-300,-930,-1900,-1500,'alpha','early alphabetic'],['phoenician','Phoenician',-470,-760,-1050,-300,'alpha','𐤀 𐤁 𐤂'],['greek-script','Greek alphabet',-690,-600,-800,2026,'alpha','Α Β Γ'],['etruscan','Etruscan alphabet',-900,-470,-700,-100,'alpha','𐌀 𐌁 𐌂'],['latin-script','Latin alphabet',-1080,-190,-650,2026,'alpha','A B C'],['aramaic-script','Aramaic alphabet',-40,-730,-800,700,'alpha','𐡀 𐡁 𐡂'],['arabic-script','Arabic script',430,420,400,2026,'alpha','ا ب ج'],['perso-arabic','Perso-Arabic',170,420,800,2026,'alpha','پ چ ژ گ'],['cyrillic','Cyrillic',-230,-160,900,2026,'alpha','А Б В'],['south-arabian','Ancient South Arabian',760,1080,-900,600,'ethiopic','𐩠 𐩡 𐩢'],['geez-script','Geʽez script',780,900,300,2026,'ethiopic','ሀ ለ ሐ'],['brahmi','Brahmi',550,1210,-300,600,'brahmic','𑀅 𑀆 𑀓'],['gupta','Gupta script',390,1030,300,650,'brahmic','Gupta'],['nagari','Nagari',120,830,650,1200,'brahmic','नागरी'],['devanagari','Devanagari',-120,600,1000,2026,'brahmic','अ आ क'],['bengali-script','Bengali–Assamese',130,590,1000,2026,'brahmic','অ আ ক'],['gurmukhi','Gurmukhi',170,470,1500,2026,'brahmic','ਅ ਆ ਕ'],['gujarati-script','Gujarati script',-240,430,1500,2026,'brahmic','અ આ ક'],['tamil-script','Tamil script',930,820,600,2026,'brahmic','அ ஆ க'],['pallava','Pallava tradition',1110,1160,400,850,'brahmic','southern Brahmic'],['telugu-script','Telugu script',1190,760,1000,2026,'brahmic','అ ఆ క'],['kannada-script','Kannada script',980,940,1000,2026,'brahmic','ಅ ಆ ಕ'],['malayalam-script','Malayalam script',1240,920,1100,2026,'brahmic','അ ആ ക'],['thai-script','Thai script',1590,520,1250,2026,'brahmic','ก ข ค'],['burmese-script','Burmese script',900,40,1000,2026,'brahmic','က ခ ဂ'],['javanese-script','Javanese script',1770,820,1200,2026,'brahmic','ꦲ ꦤ ꦕ'],['oracle','Oracle-bone writing',1510,-1110,-1300,-900,'east','early Chinese graphs'],['seal','Seal script',1590,-810,-700,200,'east','篆書'],['clerical','Clerical script',1540,-680,-200,600,'east','隸書'],['regular-hanzi','Regular Chinese characters',1440,-560,200,2026,'east','漢字'],['simplified','Simplified Chinese',1120,-520,1950,2026,'east','汉字'],['kanji','Japanese kanji',1810,-560,400,2026,'east','漢字'],['hiragana','Hiragana',1940,-500,800,2026,'east','あ い う'],['katakana','Katakana',2070,-500,800,2026,'east','ア イ ウ'],['hanja','Korean hanja',1640,-570,400,2026,'east','漢字'],['hangul','Hangul',1570,-350,1443,2026,'invented','한글'],['chu-nom','Chữ Nôm tradition',1400,80,1000,1950,'east','字喃'],['quoc-ngu','Quốc ngữ',1320,120,1650,2026,'alpha','Tiếng Việt']].map(a=>({id:a[0],name:a[1],x:a[2],y:a[3],start:a[4],end:a[5],lineage:a[6],sample:a[7]}));
const SBY=Object.fromEntries(SCRIPT.map(s=>[s.id,s])),SC={alpha:'#b995e8',brahmic:'#d4b66d',east:'#72bfd1',ethiopic:'#d18a68',invented:'#d98cae'};
const SEDGE=[['proto-sinaitic','phoenician'],['phoenician','greek-script'],['greek-script','etruscan'],['etruscan','latin-script'],['phoenician','aramaic-script'],['aramaic-script','arabic-script'],['arabic-script','perso-arabic'],['greek-script','cyrillic'],['south-arabian','geez-script'],['brahmi','gupta'],['gupta','nagari'],['nagari','devanagari'],['gupta','bengali-script'],['nagari','gujarati-script'],['gupta','gurmukhi'],['brahmi','tamil-script'],['brahmi','pallava'],['pallava','telugu-script'],['pallava','kannada-script'],['pallava','malayalam-script'],['pallava','thai-script'],['pallava','burmese-script'],['pallava','javanese-script'],['oracle','seal'],['seal','clerical'],['clerical','regular-hanzi'],['regular-hanzi','simplified'],['regular-hanzi','kanji'],['kanji','hiragana'],['kanji','katakana'],['regular-hanzi','hanja'],['regular-hanzi','chu-nom'],['latin-script','quoc-ngu']];
const SU={'latin-script':['English','Spanish','French','Portuguese','Italian','German','Dutch','Polish','Indonesian','Malay','Javanese','Filipino / Tagalog','Swahili','Turkish','Hungarian','Hausa'],'cyrillic':['Russian','Ukrainian'],'arabic-script':['Arabic'],'perso-arabic':['Persian','Urdu'],'gurmukhi':['Punjabi'],'devanagari':['Hindi','Marathi'],'bengali-script':['Bengali'],'gujarati-script':['Gujarati'],'geez-script':['Amharic'],'simplified':['Mandarin Chinese'],'regular-hanzi':['Cantonese'],'kanji':['Japanese'],'hiragana':['Japanese'],'katakana':['Japanese'],'hangul':['Korean'],'hanja':['Korean'],'quoc-ngu':['Vietnamese'],'chu-nom':['Vietnamese'],'thai-script':['Thai'],'burmese-script':['Burmese'],'tamil-script':['Tamil'],'telugu-script':['Telugu'],'kannada-script':['Kannada'],'malayalam-script':['Malayalam'],'javanese-script':['Javanese']};
const GROUPS=[{name:'PIE father cognates',kind:'cognate',anchor:'pie',refs:[['English','father'],['German','Vater'],['Dutch','vader'],['Spanish','padre'],['French','père'],['Portuguese','pai'],['Italian','padre'],['Hindi','पिता'],['Persian','پدر']]},{name:'PIE mother cognates',kind:'cognate',anchor:'pie',refs:[['English','mother'],['German','Mutter'],['Dutch','moeder'],['Spanish','madre'],['French','mère'],['Portuguese','mãe'],['Russian','мать'],['Persian','مادر']]},{name:'Tea borrowing diaspora',kind:'loan',refs:[['Mandarin Chinese','茶'],['Cantonese','茶'],['Russian','чай'],['Hindi','चाय'],['Persian','چای'],['Turkish','çay'],['Korean','차'],['Vietnamese','trà'],['Thai','ชา'],['Dutch','thee']]},{name:'Arabic kitāb borrowing web',kind:'loan',refs:[['Arabic','كتاب'],['Hindi','किताब'],['Urdu','کتاب'],['Persian','کتاب'],['Swahili','kitabu'],['Turkish','kitap']]},{name:'Coffee borrowing web',kind:'loan',refs:[['English','coffee'],['Spanish','café'],['French','café'],['Portuguese','café'],['German','Kaffee'],['Indonesian','kopi'],['Malay','kopi'],['Swahili','kahawa']]}];
const gkey=new Map();for(const g of GROUPS)for(const r of g.refs)gkey.set(r[0]+'|'+r[1].toLowerCase(),g);
function wordStart(l,w){const base=LSTART[l.name]??0,gl=String(w.g||'').toLowerCase(),src=String(w.src||'').toLowerCase();if(/computer/.test(gl))return 1940;if(/telephone/.test(gl))return 1870;if(/coffee|café/.test(gl))return w.t==='borrowed'?1500:base;if(/tea/.test(gl))return w.t==='borrowed'?1200:base;if(/book/.test(gl)&&/arabic kit/.test(src))return 1000;if(w.live)return Math.max(base,1800);if(w.t==='borrowed')return Math.max(base,800);if(w.t==='learned')return Math.max(base,1200);return base}
function englishStart(n){const l=String(n.l||'').toLowerCase();if(l.includes('proto-indo'))return -4500;if(l.includes('proto-german'))return -500;if(l.includes('old english'))return 450;if(l.includes('middle english'))return 1100;if(l.includes('old norse'))return 700;if(l.includes('latin'))return -700;if(l.includes('greek'))return -800;if(l.includes('arabic'))return 600;if(l.includes('french'))return 900;if(l.includes('japanese'))return 700;return 1400}
function resolveRef(r){const [ln,form]=r;if(ln==='English'){const n=ENS.find(n=>n.w.toLowerCase()===form.toLowerCase());return n&&active(englishStart(n))?{p:exPos(n)}:null}const l=LBY[ln],d=lex[ln];if(!l||!d||!active(LSTART[ln]??0))return null;const w=d.words.find(w=>w.f===form);if(!w||!active(wordStart(l,w)))return null;return{p:microPos(l,w,d.words.indexOf(w),d.words.length)}}
function groupFor(h){if(!h)return null;if(h.kind==='english')return gkey.get('English|'+h.obj.w.toLowerCase())||null;if(h.kind==='word')return gkey.get(h.lang.name+'|'+h.obj.f.toLowerCase())||null;return null}
function drawFamilies(){for(const f of F){const a=fade(FAMILY_START[f.id]??-4500);if(!a||!visible(f.x,f.y,600))continue;const ls=L.filter(l=>l.family===f.id),x=sx(f.x),y=sy(f.y),r=(210+ls.length*16)*cam.z,g=G.createRadialGradient(x,y,0,x,y,r*1.9);g.addColorStop(0,f.c+'30');g.addColorStop(1,f.c+'00');G.globalAlpha=a;G.fillStyle=g;G.beginPath();G.arc(x,y,r*1.9,0,7);G.fill();G.globalAlpha=1;if(cam.z<.78){G.fillStyle='#c9d8cca8';G.font='700 '+Math.max(10,16*cam.z)+'px system-ui';G.textAlign='center';G.fillText(f.name,x,y-r*.82)}}for(const [a,b] of LE){const X=npos(a),Y=npos(b);if(!X||!Y)continue;const ta=ABY[a]?ASTART[a]?.[0]:LSTART[a],tb=ABY[b]?ASTART[b]?.[0]:LSTART[b];if(year<Math.max(ta??-4500,tb??-4500))continue;line(X,Y,'#9fc3a45c',Math.max(.8,1.4*cam.z))}for(const [a,b] of BO){const X=npos(a),Y=npos(b),st=BSTART[a+'|'+b]??1200;if(X&&Y&&year>=st)line(X,Y,'#e2a46e88',1.1,[5,5],.1)}}
function drawHistorical(){if(cam.z<.34)return;for(const a of A){const t=ASTART[a.id]||[-1000,1000],al=fade(t[0],t[1]);if(!al||!visible(a.x,a.y))continue;G.globalAlpha=al;G.fillStyle='#d7bd7b';G.beginPath();G.arc(sx(a.x),sy(a.y),4*Math.max(.75,cam.z),0,7);G.fill();if(cam.z>.58){G.fillStyle='#dce9df';G.font='500 10px system-ui';G.textAlign='center';G.fillText(a.name,sx(a.x),sy(a.y)-8)}G.globalAlpha=1}}
function drawLanguages(){if(cam.z<.4)return;for(const l of L){const st=LSTART[l.name]??1200,al=fade(st);if(!al||!visible(l.x,l.y,100))continue;const f=FBY[l.family]||{c:'#607060'},is=hit?.kind==='language'&&hit.obj===l;G.globalAlpha=al;G.fillStyle=is?'#fff':f.c;G.beginPath();G.arc(sx(l.x),sy(l.y),(is?8:5)*Math.max(.8,cam.z),0,7);G.fill();if(cam.z>.5||is){G.globalAlpha=1;G.fillStyle='#eef8f0';G.font=(is?'700 ':'600 ')+Math.max(9,11*cam.z)+'px system-ui';G.textAlign='center';G.fillText(l.name,sx(l.x),sy(l.y)-9);if(cam.z>1.02){G.fillStyle='#8fa897';G.font='8px system-ui';G.fillText(l.native,sx(l.x),sy(l.y)+12)}}G.globalAlpha=1}}
const COL={inherited:'#8bc59a',borrowed:'#e2a46e',compound:'#77b6d1',derived:'#b698dc',learned:'#d7bd7b'};
function drawWords(){if(cam.z<.62)return;for(const l of L){if(year<(LSTART[l.name]??1200))continue;const d=lex[l.name];if(!d||!visible(l.x,l.y,250))continue;for(let i=0;i<d.words.length;i++){const w=d.words[i],st=wordStart(l,w),al=fade(st);if(!al)continue;const p=microPos(l,w,i,d.words.length);if(!visible(p.x,p.y,30))continue;const is=hit?.kind==='word'&&hit.lang===l&&hit.obj===w,col=COL[w.t]||'#9fc3a4';G.globalAlpha=.8*al;if(cam.z>.72)line(l,p,col+'38',.7);G.fillStyle=is?'#fff':col;G.beginPath();G.arc(sx(p.x),sy(p.y),(is?6:2.7)*Math.max(.75,cam.z),0,7);G.fill();if(cam.z>1.05||is){G.globalAlpha=1;G.fillStyle='#eaf6ec';G.font=(is?'700 ':'500 ')+'9px system-ui';G.textAlign='center';G.fillText(w.f,sx(p.x),sy(p.y)-6);if(ipaOn&&(cam.z>1.72||is)&&w.ipa){G.fillStyle='#bdebc6';G.font='8px ui-monospace,monospace';G.fillText(w.ipa,sx(p.x),sy(p.y)+9)}}G.globalAlpha=1}}}
function drawEnglish(){if(cam.z<.6||!EN||year<450||!visible(EN.x,EN.y,700))return;for(const e of EES){const a=EBY[e.a],b=EBY[e.b];if(!a||!b)continue;const sa=englishStart(a),sb=englishStart(b);if(year<Math.max(sa,sb))continue;line(exPos(a),exPos(b),(EEC[e.t]||'#79b889')+(cam.z>1?'60':'2f'),cam.z>1.2?1.2:.7,e.t==='b'?[4,4]:null,.08)}let ph=0;for(const n of ENS){const st=englishStart(n),al=fade(st);if(!al)continue;const p=exPos(n);if(!visible(p.x,p.y,30))continue;const is=hit?.kind==='english'&&hit.obj===n;G.globalAlpha=.82*al;G.fillStyle=is?'#fff':(ELC[n.l]||'#79b889');G.beginPath();G.arc(sx(p.x),sy(p.y),(is?6:2.7)*Math.max(.72,cam.z),0,7);G.fill();if(cam.z>1.05||is){G.globalAlpha=1;G.fillStyle='#eef8f0';G.font=(is?'700 ':'500 ')+'9px Georgia';G.textAlign='center';G.fillText(n.w,sx(p.x),sy(p.y)-6);if(ipaOn&&(cam.z>1.72||is)&&n.phon&&ph++<100){G.fillStyle='#bdebc6';G.font='8px ui-monospace,monospace';G.fillText(n.phon.text,sx(p.x),sy(p.y)+9)}}G.globalAlpha=1}}
function drawScripts(){if(!writingOn)return;for(const [a,b] of SEDGE){const A1=SBY[a],B1=SBY[b];if(!A1||!B1||year<B1.start)continue;line(A1,B1,(SC[B1.lineage]||'#b995e8')+'72',1.2,null,.04)}for(const [sid,names] of Object.entries(SU)){const s=SBY[sid];if(!s||!active(s.start,s.end))continue;for(const name of names){const l=LBY[name];if(l&&year>=(LSTART[name]??0))line(s,l,'#d7bd7b32',.65,[3,5],.03)}}for(const n of SCRIPT){const al=fade(n.start,n.end);if(!al||!visible(n.x,n.y,80))continue;const is=hit?.kind==='script'&&hit.obj===n,col=SC[n.lineage]||'#b995e8';G.save();G.globalAlpha=al;G.translate(sx(n.x),sy(n.y));G.rotate(Math.PI/4);G.fillStyle=is?'#fff':col;const r=(is?7:4.5)*Math.max(.78,cam.z);G.fillRect(-r,-r,r*2,r*2);G.restore();if(cam.z>.48||is){G.globalAlpha=1;G.fillStyle=is?'#fff':'#e8dffc';G.font=(is?'700 ':'600 ')+Math.max(8,10*cam.z)+'px system-ui';G.textAlign='center';G.fillText(n.name,sx(n.x),sy(n.y)-10);if((cam.z>1.2||is)&&n.sample){G.fillStyle='#cbbbe3';G.font='10px system-ui';G.fillText(n.sample,sx(n.x),sy(n.y)+13)}}G.globalAlpha=1}}
function drawGroup(){if(!cognates)return;const g=groupFor(hit);if(!g)return;const refs=g.refs.map(resolveRef).filter(Boolean);if(refs.length<2)return;const anchor=g.anchor&&ABY[g.anchor]&&active(ASTART[g.anchor]?.[0]??-4500)?{p:ABY[g.anchor]}:refs[0],col=g.kind==='cognate'?'#f2d58a':'#e2a46e';for(const r of refs){if(r===anchor)continue;line(anchor.p,r.p,col+'b5',1.6,g.kind==='loan'?[6,4]:null,.06)}}
function recentEvents(){const ev=[];for(const s of SCRIPT)if(Math.abs(s.start-year)<120)ev.push('script: '+s.name);for(const l of L){const st=LSTART[l.name];if(st!=null&&Math.abs(st-year)<120)ev.push('language: '+l.name)}for(const [k,st] of Object.entries(BSTART))if(Math.abs(st-year)<120)ev.push('contact: '+k.replace('|',' → '));return ev.slice(0,5)}
function draw(){requestAnimationFrame(draw);cam.x+=(tar.x-cam.x)*.1;cam.y+=(tar.y-cam.y)*.1;cam.z+=(tar.z-cam.z)*.1;G.fillStyle='#040806';G.fillRect(0,0,W,H);drawFamilies();drawHistorical();drawLanguages();drawWords();drawEnglish();drawGroup();drawScripts();chip.textContent=fmt(year)+' · '+stage()+' · time-filtered language + script world';if(S)S.textContent=fmt(year)+' · '+Math.round(cam.z*100)+'% · temporal model';const ev=recentEvents();eventsBox.innerHTML='<b>AROUND '+fmt(year)+'</b><br>'+(ev.length?ev.join('<br>'):'No major seeded milestone within ±120 years.')}draw();
function clearPanel(){panel?.querySelectorAll('.phon-card,.sound-card,.script-direction-card').forEach(e=>e.remove())}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function panelLanguage(l){clearPanel();panel.innerHTML=`<div class="eye">${fmt(year)} · language</div><h2>${esc(l.name)}</h2><p>${esc(l.native)}<br>${esc(l.script)}</p><div class="meta">Visible from roughly ${fmt(LSTART[l.name]??1200)} in this broad model.<br>${esc(l.history||'')}<br><br>Historical stage dates are approximate, not exact birth dates.</div>`}
function panelScript(n){clearPanel();panel.innerHTML=`<div class="eye">${fmt(year)} · writing system</div><h2>${esc(n.name)}</h2><p>${esc(n.sample)}</p><div class="meta">Modeled range: ${fmt(n.start)} → ${n.end>=2026?'present':fmt(n.end)}.<br>Diamond nodes are writing systems, not language-family ancestry.</div>`}
function panelWord(l,w){clearPanel();const st=wordStart(l,w);panel.innerHTML=`<div class="eye">${fmt(year)} · ${esc(l.name)} lexeme</div><h2>${esc(w.f)}</h2><p>${esc(w.r||'')} · ${esc(w.ipa||'')}<br><b>${esc(w.g||'')}</b></p><div class="meta">Temporal appearance here: ~${fmt(st)}.<br>${esc(w.src||'')}<br><br>This individual-word date is ${w.live?'source-connected but not necessarily first-attestation dated':'heuristic unless explicitly sourced'}.</div>`}
function panelAncestor(a){const t=ASTART[a.id]||[-1000,1000];panel.innerHTML=`<div class="eye">${fmt(year)} · historical language stage</div><h2>${esc(a.name)}</h2><div class="meta">Broad modeled range: ${fmt(t[0])} → ${fmt(t[1])}.</div>`}
function panelEnglish(n){const st=englishStart(n);panel.innerHTML=`<div class="eye">${fmt(year)} · English lineage</div><h2>${esc(n.w)}</h2><p>${esc(n.l)} · ${esc(n.era)}<br>${esc(n.m)}</p><div class="meta">Visible from roughly ${fmt(st)} in the temporal model.</div>`}
function focus(x,y,z=.9){tar.x=x;tar.y=y;tar.z=Math.max(tar.z,z)}
function chooseAt(px,py){let best=null,dist=25;if(writingOn)for(const n of SCRIPT){if(!active(n.start,n.end))continue;const q=Math.hypot(sx(n.x)-px,sy(n.y)-py);if(q<dist){dist=q;best={kind:'script',obj:n}}}for(const l of L){if(year<(LSTART[l.name]??1200))continue;const q=Math.hypot(sx(l.x)-px,sy(l.y)-py);if(q<dist){dist=q;best={kind:'language',obj:l}}}for(const a of A){const t=ASTART[a.id]||[-1000,1000];if(!active(t[0],t[1]))continue;const q=Math.hypot(sx(a.x)-px,sy(a.y)-py);if(q<dist){dist=q;best={kind:'ancestor',obj:a}}}if(cam.z>.6)for(const l of L){if(year<(LSTART[l.name]??1200))continue;const d=lex[l.name];if(!d)continue;for(let i=0;i<d.words.length;i++){const w=d.words[i];if(year<wordStart(l,w))continue;const p=microPos(l,w,i,d.words.length),q=Math.hypot(sx(p.x)-px,sy(p.y)-py);if(q<dist){dist=q;best={kind:'word',lang:l,obj:w,p}}}}if(cam.z>.62)for(const n of ENS){if(year<englishStart(n))continue;const p=exPos(n),q=Math.hypot(sx(p.x)-px,sy(p.y)-py);if(q<dist){dist=q;best={kind:'english',obj:n,p}}}return best}
function select(h){if(!h)return;hit=h;if(h.kind==='script'){panelScript(h.obj);focus(h.obj.x,h.obj.y,.82)}else if(h.kind==='language'){panelLanguage(h.obj);focus(h.obj.x,h.obj.y,.72)}else if(h.kind==='ancestor'){panelAncestor(h.obj);focus(h.obj.x,h.obj.y,.72)}else if(h.kind==='word'){panelWord(h.lang,h.obj);focus(h.p.x,h.p.y,1.15)}else if(h.kind==='english'){panelEnglish(h.obj);focus(h.p.x,h.p.y,1.15)}}
function search(q){q=q.trim().toLowerCase();if(!q)return false;let s=SCRIPT.find(x=>x.name.toLowerCase().includes(q)&&active(x.start,x.end));if(s){select({kind:'script',obj:s});return true}let l=L.find(x=>x.name.toLowerCase().startsWith(q)&&year>=(LSTART[x.name]??1200));if(l){select({kind:'language',obj:l});return true}let a=A.find(x=>x.name.toLowerCase().includes(q)&&active((ASTART[x.id]||[-1000,1000])[0],(ASTART[x.id]||[-1000,1000])[1]));if(a){select({kind:'ancestor',obj:a});return true}let en=ENS.find(n=>n.w.toLowerCase()===q&&year>=englishStart(n));if(en){select({kind:'english',obj:en,p:exPos(en)});return true}for(const l of L){if(year<(LSTART[l.name]??1200))continue;const d=lex[l.name];if(!d)continue;const w=d.words.find(w=>year>=wordStart(l,w)&&[w.f,w.r,w.g].some(v=>String(v||'').toLowerCase()===q));if(w){select({kind:'word',lang:l,obj:w,p:microPos(l,w,d.words.indexOf(w),d.words.length)});return true}}return false}
function setYear(v){year=Math.max(-4500,Math.min(2026,Math.round(Number(v)/25)*25));slider.value=year;yearEl.textContent=fmt(year);if(hit){const valid=hit.kind==='script'?active(hit.obj.start,hit.obj.end):hit.kind==='language'?year>=(LSTART[hit.obj.name]??1200):hit.kind==='ancestor'?active(...(ASTART[hit.obj.id]||[-1000,1000])):hit.kind==='word'?year>=wordStart(hit.lang,hit.obj):hit.kind==='english'?year>=englishStart(hit.obj):true;if(!valid)hit=null}}
slider.oninput=()=>setYear(slider.value);nowBtn.onclick=()=>{playing=false;clearInterval(timer);playBtn.textContent='▶';setYear(2026)};playBtn.onclick=()=>{playing=!playing;playBtn.textContent=playing?'❚❚':'▶';clearInterval(timer);if(!playing)return;if(year>=2026)setYear(-4500);timer=setInterval(()=>{if(year>=2026){playing=false;clearInterval(timer);playBtn.textContent='▶';return}setYear(year+25)},90)};
U.onpointerdown=e=>{pts.set(e.pointerId,[e.clientX,e.clientY]);U.setPointerCapture(e.pointerId);moved=0};U.onpointermove=e=>{if(!pts.has(e.pointerId))return;const old=pts.get(e.pointerId);pts.set(e.pointerId,[e.clientX,e.clientY]);if(pts.size===1){const dx=e.clientX-old[0],dy=e.clientY-old[1];if(Math.hypot(dx,dy)>2)moved=1;cam.x=tar.x-=dx/cam.z;cam.y=tar.y-=dy/cam.z}else{const p=[...pts.values()],d=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]),mx=(p[0][0]+p[1][0])/2,my=(p[0][1]+p[1][1])/2;if(pinch){const bx=wx(mx),by=wy(my),z=Math.max(.18,Math.min(3.4,cam.z*d/pinch));cam.z=tar.z=z;cam.x=tar.x=bx-(mx-W/2)/z;cam.y=tar.y=by-(my-H/2)/z}pinch=d;moved=1}};function up(e){pts.delete(e.pointerId);if(pts.size<2)pinch=0}U.onpointerup=up;U.onpointercancel=up;U.addEventListener('wheel',e=>{e.preventDefault();const bx=wx(e.clientX),by=wy(e.clientY),z=Math.max(.18,Math.min(3.4,cam.z*Math.exp(-e.deltaY*.0012)));cam.z=tar.z=z;cam.x=tar.x=bx-(e.clientX-W/2)/z;cam.y=tar.y=by-(e.clientY-H/2)/z},{passive:false});U.onclick=e=>{if(!moved)select(chooseAt(e.clientX,e.clientY))};
function replace(id,handler,label){const o=document.querySelector(id);if(!o)return null;const n=o.cloneNode(true);if(label)n.textContent=label;o.replaceWith(n);n.onclick=handler;return n}
const qOld=document.querySelector('#q'),q=qOld?.cloneNode(true);if(qOld&&q){qOld.replaceWith(q);q.onkeydown=e=>{if(e.key==='Enter'&&!search(q.value))if(typeof toast==='function')toast('Not visible at '+fmt(year))}}replace('#go',()=>{if(!search(q?.value||''))if(typeof toast==='function')toast('Not visible at '+fmt(year))});replace('#atlas',()=>{tar={x:430,y:100,z:.33};hit=null},'Atlas');replace('#home',()=>{if(year<450)setYear(450);tar={x:EN.x,y:EN.y,z:.78};hit={kind:'language',obj:EN};panelLanguage(EN)},'English');replace('#worldMode',()=>{tar={x:430,y:100,z:.33};hit=null},'World');
const wr=document.querySelector('#writingTreeBtn');if(wr)wr.addEventListener('click',()=>{writingOn=!writingOn});const cog=document.querySelector('#cognateBtn');if(cog)cog.addEventListener('click',()=>{cognates=!cognates});const ipa=document.querySelector('#ipa-toggle');if(ipa)ipa.addEventListener('click',()=>{ipaOn=!ipaOn});const ch=document.querySelector('.sound-toggle');if(ch)ch.addEventListener('click',()=>{changesOn=!changesOn});let tb=document.querySelector('#timeBtn');if(tb)tb.remove();tb=document.createElement('button');tb.id='timeBtn';tb.className='on';tb.textContent='Time';tb.title='Temporal evolution mode';document.querySelector('.btns')?.insertBefore(tb,document.querySelector('#home'));tb.onclick=()=>{bar.style.display=bar.style.display==='none'?'block':'none'};
document.body.classList.add('temporal-world');document.querySelector('.writing-chip')?.remove();document.querySelector('.writing-key')?.remove();const sm=document.querySelector('.brand small');if(sm)sm.textContent='Phase 6.0 · temporal language + writing evolution';panel.innerHTML='<div class="eye">temporal evolution</div><h2>History is now a dimension</h2><p>Drag the timeline from 4500 BCE to the present.</p><div class="meta">Languages, historical stages, scripts, borrowing routes and word layers appear as the modeled date reaches them. Exactness varies: large historical stages are approximate ranges; many individual lexeme dates are heuristic until source-backed.</div>';setYear(2026);
})();